# Qiskit: Quantum Gates
* Last updated on 10/04/2023

In [1]:
import numpy as np

In [2]:
from qiskit.circuit.library import *

## Identity gate

## Pauli gates (X, Y, Z)

## Controlled gates

## Phase shift gates
* https://docs.quantum-computing.ibm.com/api/qiskit/qiskit.circuit.library.PhaseGate
* qiskit.circuit.library.PhaseGate()
* QuantumCircuit.p()

### ZGate = PhaseGate($\pi$)

In [3]:
PhaseGate(np.pi).to_matrix()

array([[ 1.+0.0000000e+00j,  0.+0.0000000e+00j],
       [ 0.+0.0000000e+00j, -1.+1.2246468e-16j]])

In [4]:
ZGate().to_matrix()

array([[ 1.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j]])

### SGate = PhaseGate($\pi/2$)

In [5]:
PhaseGate(np.pi/2).to_matrix()

array([[1.000000e+00+0.j, 0.000000e+00+0.j],
       [0.000000e+00+0.j, 6.123234e-17+1.j]])

In [6]:
SGate().to_matrix()

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j]])

### TGate = PhaseGate($\pi/4$)

In [7]:
PhaseGate(np.pi/4).to_matrix()

array([[1.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.70710678+0.70710678j]])

In [8]:
TGate().to_matrix()

array([[1.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.70710678+0.70710678j]])

## Hadamard gate (H)
* https://docs.quantum-computing.ibm.com/api/qiskit/qiskit.circuit.library.HGate

In [9]:
HGate().to_matrix()

array([[ 0.70710678+0.j,  0.70710678+0.j],
       [ 0.70710678+0.j, -0.70710678+0.j]])